In [22]:
# import packages
import numpy as np

In [23]:
# create a dummy dataset
x = np.random.randint(50,90,100).reshape(20,5)
print(x)

[[75 56 74 81 75]
 [81 57 51 86 51]
 [67 65 77 88 59]
 [77 64 82 52 69]
 [83 85 57 56 51]
 [87 78 73 55 79]
 [78 69 50 55 72]
 [60 63 50 51 89]
 [73 54 80 53 60]
 [56 85 61 82 63]
 [66 69 61 50 67]
 [76 63 79 80 66]
 [87 88 78 73 62]
 [57 55 60 88 67]
 [72 52 73 78 59]
 [60 72 86 60 79]
 [79 53 56 54 70]
 [51 75 86 73 64]
 [54 61 81 76 78]
 [58 86 77 63 80]]


In [24]:
 # mean centering the data
 xmean=x-np.mean(x,axis=0)
 xmean

array([[  5.15, -11.5 ,   4.4 ,  13.3 ,   7.  ],
       [ 11.15, -10.5 , -18.6 ,  18.3 , -17.  ],
       [ -2.85,  -2.5 ,   7.4 ,  20.3 ,  -9.  ],
       [  7.15,  -3.5 ,  12.4 , -15.7 ,   1.  ],
       [ 13.15,  17.5 , -12.6 , -11.7 , -17.  ],
       [ 17.15,  10.5 ,   3.4 , -12.7 ,  11.  ],
       [  8.15,   1.5 , -19.6 , -12.7 ,   4.  ],
       [ -9.85,  -4.5 , -19.6 , -16.7 ,  21.  ],
       [  3.15, -13.5 ,  10.4 , -14.7 ,  -8.  ],
       [-13.85,  17.5 ,  -8.6 ,  14.3 ,  -5.  ],
       [ -3.85,   1.5 ,  -8.6 , -17.7 ,  -1.  ],
       [  6.15,  -4.5 ,   9.4 ,  12.3 ,  -2.  ],
       [ 17.15,  20.5 ,   8.4 ,   5.3 ,  -6.  ],
       [-12.85, -12.5 ,  -9.6 ,  20.3 ,  -1.  ],
       [  2.15, -15.5 ,   3.4 ,  10.3 ,  -9.  ],
       [ -9.85,   4.5 ,  16.4 ,  -7.7 ,  11.  ],
       [  9.15, -14.5 , -13.6 , -13.7 ,   2.  ],
       [-18.85,   7.5 ,  16.4 ,   5.3 ,  -4.  ],
       [-15.85,  -6.5 ,  11.4 ,   8.3 ,  10.  ],
       [-11.85,  18.5 ,   7.4 ,  -4.7 ,  12.  ]])

In [25]:
#calculate the covariance of the mean-centered data
covar=np.cov(xmean, rowvar=False)
covar

array([[ 1.30871053e+02, -7.89473684e-02, -2.82736842e+01,
        -3.58894737e+01, -3.78421053e+01],
       [-7.89473684e-02,  1.42052632e+02,  1.61578947e+01,
        -2.62105263e+01,  2.68421053e+00],
       [-2.82736842e+01,  1.61578947e+01,  1.54673684e+02,
         2.30315789e+01,  1.17368421e+01],
       [-3.58894737e+01, -2.62105263e+01,  2.30315789e+01,
         1.95063158e+02, -5.11052632e+01],
       [-3.78421053e+01,  2.68421053e+00,  1.17368421e+01,
        -5.11052632e+01,  9.91578947e+01]])

In [26]:
# eigenvalue of the covariance matrix
eigen_values , eigen_vectors = np.linalg.eigh(covar)
eigen_values

array([ 46.54707558, 112.95570208, 141.50920081, 186.6126679 ,
       234.19377468])

In [27]:
# eigenvector of the covariance matrix
eigen_vectors

array([[ 0.49559841,  0.46958161, -0.45203264,  0.49292371, -0.29422447],
       [ 0.09997176, -0.54179589, -0.72165109, -0.36700639, -0.20245711],
       [-0.05439946,  0.66226759, -0.25601665, -0.64369649,  0.28027245],
       [ 0.40695841, -0.20271209, -0.12639314,  0.18285305,  0.86248606],
       [ 0.7588237 , -0.0791188 ,  0.43973452, -0.41779436, -0.22362521]])

In [28]:
# sort the index of column
sorted_index = np.argsort(eigen_values)[::-1]
sorted_index

array([4, 3, 2, 1, 0])

In [29]:
# sort the eigenvector in descending order
sorted_eigenvectors = eigen_vectors[:,sorted_index]
sorted_eigenvectors

array([[-0.29422447,  0.49292371, -0.45203264,  0.46958161,  0.49559841],
       [-0.20245711, -0.36700639, -0.72165109, -0.54179589,  0.09997176],
       [ 0.28027245, -0.64369649, -0.25601665,  0.66226759, -0.05439946],
       [ 0.86248606,  0.18285305, -0.12639314, -0.20271209,  0.40695841],
       [-0.22362521, -0.41779436,  0.43973452, -0.0791188 ,  0.7588237 ]])

In [30]:
# sort the eigenvalue in descending order
sorted_eigenvalue = eigen_values[sorted_index]
sorted_eigenvalue

array([234.19377468, 186.6126679 , 141.50920081, 112.95570208,
        46.54707558])

In [31]:
# sort the first n eigenvectors, n is decreased dimension of our final reduced data
n = 2 
eigenvector_subset = sorted_eigenvectors[:, 0:n]
eigenvector_subset

array([[-0.29422447,  0.49292371],
       [-0.20245711, -0.36700639],
       [ 0.28027245, -0.64369649],
       [ 0.86248606,  0.18285305],
       [-0.22362521, -0.41779436]])

In [32]:
# transform the data and print the reduced dimension
X_reduced = np.dot(eigenvector_subset.transpose(),xmean.transpose()).transpose()
X_reduced

array([[ 11.95188758,   3.43425108],
       [ 13.21725259,  31.77113597],
       [ 22.93979251,   2.22139554],
       [-11.68438292,  -6.46149688],
       [-17.23294236,  13.13303409],
       [-19.63227321,  -4.50646521],
       [-20.04302896,  12.08985863],
       [-20.78381868,  -2.41464603],
       [ -6.16834588,   0.46726738],
       [ 11.57334303,  -3.01004486],
       [-16.62364253,   0.26881929],
       [ 12.79196648,   1.71694379],
       [ -0.92910443,  -1.00115253],
       [ 21.35297488,   8.56270779],
       [ 14.35466222,  10.20335252],
       [ -2.51749768, -23.06715608],
       [-15.83154057,  15.24544124],
       [ 14.08984814, -19.96048359],
       [ 14.09691717, -15.42570245],
       [ -4.92206741, -23.26705969]])